### PR TITLE
more reduction tests

### PR DESCRIPTION
**Pull request by keewis**
- [x] follow-up to #2

This adds a few more reduction (or index reduction) tests, which should cover everything `xarray` supports and which is part of the array API. `xarray` additionally provides sorting-based reductions like `quantile` and `median`, plus `rank` which I don't quite understand.

### CODE REVIEW

**Comment by keewis** [comment]
looks like `numpy<2.1` didn't have `cumulative_sum`, so we'll have to wait until `xarray` supports `numpy=2.1` (i.e. whenever we get around to releasing a new version).

We could probably merge `all`, `any`, `min`, and `max` into the main `reduce` test, but I do like the clear separation that gives us (even though we duplicate the code twice).

Other than that, this should be ready for review, @TomNicholas

**Comment by keewis** [comment]
looks like that finally did it. So with that we only need to decide what to do about the code duplication (or if we can, as I would suggest, leave it as is), and this should be good to merge.

**Comment by keewis** [comment]
assuming that the code duplication is nothing urgent, I'm going to go ahead and merge

**Comment by TomNicholas** [comment]
Sorry Justus! This looks great though.

**Pull request merged**
